spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/config-info/config-info-master/{application}
          order: 1
